# application.yml   SpringBoot \u914D\u7F6E\u6587\u4EF6

# \u670D\u52A1\u5668\u7AEF\u53E3
server:
    port: 8080

# \u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tilas?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis\u914D\u7F6E
mybatis:
    configuration:
        map-underscore-to-camel-case: true  # \u5173\u952E\u914D\u7F6E
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # \u5F00\u542FSQL\u65E5\u5FD7
    mapper-locations: classpath:mapper/*.xml